version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/node:carbon

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - dependencies-{{ checksum "package-lock.json" }}
          # fallback to using the latest cache if no exact match is found
          - dependencies-

      - run: npm install

      - save_cache:
          paths:
            - node_modules
          key: dependencies-{{ checksum "package-lock.json" }}

      # run linting
      - run: npm run lint

      # run tests!
      - run: npm run test:ci
